services:
  govanityurls:
     image: maxnilz/govanityurls:0.1.0
     volumes:
      - ./vanity.yaml:/etc/vanity.yaml:ro
     networks:
       - pegasus
  goproxy:
    image: ogre0403/goproxy:latest
    environment:
      GOINSECURE: "pegasus-cloud.com"
      GOSUMDB: "off"
    ports:
    - "8078:8078"
    extra_hosts:
      - "pegasus-cloud.com:127.0.0.1"
    networks:
      - pegasus    


networks:
  pegasus:
    driver: bridge