services:
  trust-cloud-proxy:
    container_name: goproxy
    image: ogre0403/goproxy:latest
    environment:
      - REPO_TOKEN=${REPO_TOKEN}
      - SRC_REPO=${SRC_REPO}
      - DEST_REPO=${DEST_REPO}
    networks:
      proxy-network: {}
    ports:
      - "8078:8078"
    restart: on-failure

networks:
  proxy-network:
    name: proxy-network
    driver: bridge
  pegasus-cloud-network:
    external: true
    name: pegasus-cloud-network
